---
# Main tasks for the duffy role

- tags:
    - duffy
  block:
    - name: Import distro-specific variables
      include_vars: "{{ item }}"
      register: included_file
      failed_when: >-
        included_file.ansible_included_var_files | length > 0 and not included_file.ansible_facts
      loop:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      tags:
        - vars

    - name: Install packages needed for Duffy
      package:
        name: "{{ duffy_dev_pkgs + duffy_python_pkgs | list }}"
        state: present
      tags:
        - pkgs

    - name: Create the duffy Unix user
      user:
        name: duffy
        home: /home/duffy
        generate_ssh_key: yes
        local: yes
      register: duffy_user
      tags:
        - users

    - name: Perform SELinux-related changes
      import_tasks: selinux.yml
      tags:
        - selinux

    - name: Allow access to the Duffy web apps
      include_role:
        name: iptables
        tasks_from: custom-policy
      vars:
        iptables_policy_name: "duffy-{{ item.key }}"
        iptables_protocol: tcp
        iptables_port: "{{ item.value }}"
        iptables_source: "0.0.0.0/0"
      loop: '{{ {"app": duffy_app_port, "metaclient": duffy_metaclient_port} | dict2items }}'
      tags:
        - iptables

    # The postgresql (server) role is listed in the role metadata.

    - name: Set up PostgreSQL client and Duffy database
      import_tasks: postgresql.yml
      tags:
        - postgresql

    - name: Install Duffy Python package
      pip:
        name: "duffy[tasks,postgresql,interactive,legacy]"
        version: "=={{ duffy_app_version }}"
        virtualenv: "{{ duffy_venv }}"
        virtualenv_command: "{{ duffy_python_executable }} -m venv"
      tags:
        - pkgs
      notify:
        - restart_duffy

    - become_user: duffy
      tags:
        - files
      block:
        - name: "Install ~/bin directory for the Duffy user"
          file:
            path: "/home/duffy/bin"
            state: directory
            mode: u=rwx,go=rx

        - name: Install the duffy command wrapper for the Duffy user
          template:
            src: "duffy.sh.j2"
            dest: "/home/duffy/bin/duffy"
            owner: duffy
            group: duffy
            follow: no
            mode: u=rwx,go=rx

    - name: Create Duffy configuration directory
      file:
        path: /etc/duffy
        state: directory
      tags:
        - files

    - name: Create Duffy tasks schedule directory
      file:
        path: "{{ duffy_tasks_schedule_filename | dirname }}"
        state: directory
        owner: duffy
        group: duffy
      tags:
        - files

    - name: Install Duffy configuration files
      notify: restart_duffy
      tags:
        - config
        - files
      block:
        - name: Install templated Duffy configuration files
          template:
            src: "config/{{ item }}.yaml.j2"
            dest: "/etc/duffy/{{ item }}.yaml"
            owner: root
            group: duffy
            mode: "u=rw,g=r,o={{ ('secret' in item) | ternary('', 'r') }}"
          loop: "{{ duffy_config_files }}"

        - name: Install Duffy node pool configuration
          copy:
            src: "{{ filestore }}/duffy/{{ duffy_node_pool_config_file }}"
            dest: "/etc/duffy/70_nodepools.yaml"
            owner: root
            group: duffy
            mode: "u=rw,go=r"

        - name: Remove obsolete configuration files
          file:
            path: "/etc/duffy/{{ item }}.yaml"
            state: absent
          loop: "{{ duffy_config_files_remove }}"

    - become_user: duffy
      tags:
        - database
      environment:
        PATH: "/home/duffy/bin:{{ ansible_env.PATH }}"
      block:
        - name: Set up Duffy database schema
          command: duffy setup-db
          register: duffy_setup_db_out
          changed_when: not duffy_setup_db_out.failed
          failed_when: >-
            duffy_setup_db_out.failed
            and "Refusing to change database schema" not in duffy_setup_db_out.stderr

        - name: Apply database schema migrations
          command: duffy migration upgrade
          register: duffy_migration_upgrade_out
          changed_when: >-
            not duffy_migration_upgrade_out.failed
            and "Upgraded to" in duffy_migration_upgrade_out.stdout

    - tags:
      - services
      block:
        - name: Install Duffy systemd services
          template:
            src: "systemd/{{ item }}.j2"
            dest: "/etc/systemd/system/{{ item }}"
          notify:
            - "Restart {{ item }}"
          register: install_systemd_services
          loop:
            - duffy-app.service
            - duffy-metaclient.service
            - duffy-tasks.service

        - name: Install shared systemd environment file
          template:
            src: systemd/duffy.sysconfig.j2
            dest: /etc/sysconfig/duffy
          notify:
            - restart_duffy

        - name: Let systemd know about new units
          systemd:
            daemon_reload: yes
          when: install_systemd_services.changed

        - name: Enable Duffy systemd services
          systemd:
            name: "{{ item }}"
            enabled: yes
          loop:
            - duffy-app.service
            - duffy-metaclient.service
            - duffy-tasks.service

    - name: Ensure admin tenant exists and is configured properly
      become_user: duffy
      environment:
        PATH: "/home/duffy/bin:{{ ansible_env.PATH }}"
      tags:
        - admin-tenant
      block:
        - name: Check if admin tenant exists
          command: "duffy tenant show {{ duffy_admin_tenant }}"
          register: admin_tenant_exists
          failed_when: False
          changed_when: admin_tenant_exists.rc == 0

        - name: Create admin tenant
          command:
            argv:
              - duffy
              - tenant
              - create
              - --is-admin
              - "{{ duffy_admin_tenant }}"
              - "{{ duffy_admin_ssh_key }}"
          when: admin_tenant_exists.rc != 0

        - name: Set API key of admin tenant
          command: >-
            duffy tenant update {{ duffy_admin_tenant }} --api-key {{ duffy_admin_api_key }}
          when: >-
            admin_tenant_exists.rc != 0
            and duffy_admin_api_key != "please override this in production"
 
        - name: Ensuring duffy user can write to some directories for provisioning
          acl:
            entity: duffy
            etype: user
            path: "{{ item }}"
            permissions: rwx
            state: present
          with_items:
            - /var/lib/tftpboot/pxelinux.cfg/
            - /var/www/html/ks/
          delegate_to: "{{ duffy_boot_server }}"
          tags:
            - acls
