---
# SELinux tasks for the duffy role

- name: Ensure files in virtualenv are executable by systemd
  sefcontext:
    target: "{{ duffy_venv }}(/.*)?"
    setype: "lib_t"
  tags:
    - files

- name: Relabel existing files in virtualenv
  command: "restorecon -irv {{ duffy_venv }}"
  tags:
    - files
  register: relabel_out
  changed_when: relabel_out.stdout | length
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: Ensure Duffy processes can mmap files and connect to tcp sockets
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: true
  loop:
    - domain_can_mmap_files
    - nis_enabled
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: Distributing custom selinux policy file[s]
  copy:
    src: "selinux/{{ ansible_distribution_major_version }}/{{ item }}"
    dest: "/etc/selinux/centos/{{ item }}"
  with_items:
    - centos-duffy.pp
  register: sepolicy  
  tags:
    - selinux

- name: Reloading selinux policy on change
  shell: "/usr/sbin/semodule -u /etc/selinux/centos/{{ item.item }}"
  with_items: "{{ sepolicy.results }}"
  when: item.changed
  no_log: True
  tags:
    - selinux
    
