---
# Handlers for the Duffy role

- name: Restart duffy-app.service
  systemd:
    name: duffy-app.service
    state: restarted

- name: Restart duffy-metaclient.service
  systemd:
    name: duffy-metaclient.service
    state: restarted

- name: Restart duffy-tasks.service
  systemd:
    name: duffy-tasks.service
    state: restarted

- name: restart_duffy
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - duffy-app.service
    - duffy-metaclient.service
    - duffy-tasks.service

